### ISSUE TITLE
Dependency errors on newest Raspbian

### ISSUE THREAD

**Issue by franky384** [kecsap/robot_telescope#1]
Build dependencies don't install on new Raspbian Stretch:
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 libmindaibo-dev : Hängt ab von: libmindaibo (= 3.1.2~rpi14) soll aber nicht installiert werden
 libmindeye-dev : Hängt ab von: libmindeye (= 3.1.2~rpi14) soll aber nicht installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
Which raspbian version have you installed this on ?
I also tried to install it on Ubuntu xenial for Pi , same problem.

**Comment by kecsap** [comment]
Sorry for the delay. Now I updated my Ubuntu PPA and the dependencies can be also downloaded for Raspbian Stretch. The instructions are updated.

**Comment by franky384** [comment]
Great, thank you !
